obj-y += board.o

obj-y += clock.o clock-debug.o
obj-y += clock-8960.o
obj-y += clock-pll.o
obj-y += clock-local.o
obj-y += clock-voter.o
obj-y += clock-rpm.o

obj-y += rpm.o
obj-y += rpm-regulator.o
obj-y += rpm-regulator-8960.o
obj-y += rpm_resources.o

obj-y += io.o

obj-y += board-8960-gpiomux.o
obj-y += gpiomux-v2.o gpiomux.o
