/* Copyright (c) 2011-2012, Code Aurora Forum. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __ASM_ARCH_MSM_IRQS_8960_H
#define __ASM_ARCH_MSM_IRQS_8960_H

/* MSM ACPU Interrupt Numbers */

/* 0-15:  STI/SGI (software triggered/generated interrupts)
   16-31: PPI (private peripheral interrupts)
   32+:   SPI (shared peripheral interrupts) */

#define GIC_PPI_START 0
#define GIC_SPI_START 0

#define INT_VGIC				(0)
#define INT_DEBUG_TIMER_EXP			(0)
#define INT_GP_TIMER_EXP			(0)
#define INT_GP_TIMER2_EXP			(0)
#define WDT0_ACCSCSSNBARK_INT			(0)
#define WDT1_ACCSCSSNBARK_INT			(0)
#define AVS_SVICINT				(0)
#define AVS_SVICINTSWDONE			(0)
#define CPU_DBGCPUXCOMMRXFULL			(0)
#define CPU_DBGCPUXCOMMTXEMPTY			(0)
#define INT_ARMQC_PERFMON			(0)
#define SC_AVSCPUXDOWN				(0)
#define SC_AVSCPUXUP				(0)
#define SC_SICCPUXACGIRPTREQ			(0)
#define SC_SICCPUXEXTFAULTIRPTREQ		(0)
/* PPI 15 is unused */

#define APCC_QGICACGIRPTREQ			(0)
#define APCC_QGICL2PERFMONIRPTREQ		(0)
#define SC_SICL2PERFMONIRPTREQ			0
#define APCC_QGICL2IRPTREQ			(0)
#define APCC_QGICMPUIRPTREQ			(0)
#define TLMM_MSM_DIR_CONN_IRQ_0			(0)
#define TLMM_MSM_DIR_CONN_IRQ_1			(0)
#define TLMM_MSM_DIR_CONN_IRQ_2			(0)
#define TLMM_MSM_DIR_CONN_IRQ_3			(0)
#define TLMM_MSM_DIR_CONN_IRQ_4			(0)
#define TLMM_MSM_DIR_CONN_IRQ_5			(0)
#define TLMM_MSM_DIR_CONN_IRQ_6			(0)
#define TLMM_MSM_DIR_CONN_IRQ_7			(0)
#define TLMM_MSM_DIR_CONN_IRQ_8			(0)
#define TLMM_MSM_DIR_CONN_IRQ_9			(0)
#define PM8921_SEC_IRQ_103			(0)
#define PM8018_SEC_IRQ_106			(0)
/*  Summary IRQ for Apps DSP  */
//  I would prefer to use irq_find_mapping here, but these are used as static initializers.
//  Actually it should probably be in device tree.
//  So this happens to assume that irqdomains are used, and the h2-pic virq's are just offset by 1.
//  Yes, dirty.
#define TLMM_MSM_SUMMARY_IRQ			(38+32 + 1)
#define SPDM_RT_1_IRQ				(0)
#define SPDM_DIAG_IRQ				(0)

#define RPM_APCC_CPU0_GP_HIGH_IRQ		(0)
#define RPM_APCC_CPU0_GP_MEDIUM_IRQ		(0)
#define RPM_APCC_CPU0_GP_LOW_IRQ		(0)

/*  l2vic interrupt offset is 32  */
#ifdef CONFIG_HEXAGON
#define RPM_LPASS_GP_LOW_IRQ			(45+32 + 1)
#define RPM_LPASS_GP_MEDIUM_IRQ			(44+32 + 1)
#define RPM_LPASS_GP_HIGH_IRQ			(28+32 + 1)
#define RPM_LPASS_Q6SS_WAKE_UP_IRQ		(96+32 + 1)
#endif

#define RPM_APCC_CPU0_WAKE_UP_IRQ		(0)
#define RPM_APCC_CPU1_GP_HIGH_IRQ		(0)
#define RPM_APCC_CPU1_GP_MEDIUM_IRQ		(0)
#define RPM_APCC_CPU1_GP_LOW_IRQ		(0)
#define RPM_APCC_CPU1_WAKE_UP_IRQ		(0)
#define SSBI2_2_SC_CPU0_SECURE_IRQ		(0)
#define SSBI2_2_SC_CPU0_NON_SECURE_IRQ		(0)
#define SSBI2_1_SC_CPU0_SECURE_IRQ		(0)
#define SSBI2_1_SC_CPU0_NON_SECURE_IRQ		(0)
#define MSMC_SC_SEC_CE_IRQ			(0)
#define MSMC_SC_PRI_CE_IRQ			(0)
#define SLIMBUS0_CORE_EE1_IRQ			(0)
#define SLIMBUS0_BAM_EE1_IRQ			(0)
#define Q6FW_WDOG_EXPIRED_IRQ			(0)
#define Q6SW_WDOG_EXPIRED_IRQ			(0)
#define MSS_TO_APPS_IRQ_0			(0)
#define MSS_TO_APPS_IRQ_1			(0)
#define MSS_TO_APPS_IRQ_2			(0)
#define MSS_TO_APPS_IRQ_3			(0)
#define MSS_TO_APPS_IRQ_4			(0)
#define MSS_TO_APPS_IRQ_5			(0)
#define MSS_TO_APPS_IRQ_6			(0)
#define MSS_TO_APPS_IRQ_7			(0)
#define MSS_TO_APPS_IRQ_8			(0)
#define MSS_TO_APPS_IRQ_9			(0)
#define VPE_IRQ					(0)
#define VFE_IRQ					(0)
#define VCODEC_IRQ				(0)
#define TV_ENC_IRQ				(0)
#define SMMU_VPE_CB_SC_SECURE_IRQ		(0)
#define SMMU_VPE_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_VFE_CB_SC_SECURE_IRQ		(0)
#define SMMU_VFE_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_VCODEC_B_CB_SC_SECURE_IRQ		(0)
#define SMMU_VCODEC_B_CB_SC_NON_SECURE_IRQ	(0)
#define SMMU_VCODEC_A_CB_SC_SECURE_IRQ		(0)
#define SMMU_VCODEC_A_CB_SC_NON_SECURE_IRQ	(0)
#define SMMU_ROT_CB_SC_SECURE_IRQ		(0)
#define SMMU_ROT_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_MDP1_CB_SC_SECURE_IRQ		(0)
#define SMMU_MDP1_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_MDP0_CB_SC_SECURE_IRQ		(0)
#define SMMU_MDP0_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_JPEGD_CB_SC_SECURE_IRQ		(0)
#define SMMU_JPEGD_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_IJPEG_CB_SC_SECURE_IRQ		(0)
#define SMMU_IJPEG_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_GFX3D_CB_SC_SECURE_IRQ		(0)
#define SMMU_GFX3D_CB_SC_NON_SECURE_IRQ		(0)
#define SMMU_GFX2D0_CB_SC_SECURE_IRQ		(0)
#define SMMU_GFX2D0_CB_SC_NON_SECURE_IRQ	(0)
#define ROT_IRQ					(0)
#define MMSS_FABRIC_IRQ				(0)
#define MDP_IRQ					(0)
#define JPEGD_IRQ				(0)
#define JPEG_IRQ				(0)
#define MMSS_IMEM_IRQ				(0)
#define HDMI_IRQ				(0)
#define GFX3D_IRQ				(0)
#define GFX2D0_IRQ				(0)
#define DSI1_IRQ				(0)
#define CSI_1_IRQ				(0)
#define CSI_0_IRQ				(0)
#define LPASS_SCSS_AUDIO_IF_OUT0_IRQ		(0)
#define LPASS_SCSS_MIDI_IRQ			(0)
#define LPASS_Q6SS_WDOG_EXPIRED			(0)
#define LPASS_SCSS_GP_LOW_IRQ			(0)
#define LPASS_SCSS_GP_MEDIUM_IRQ		(0)
#define LPASS_SCSS_GP_HIGH_IRQ			(0)
#define TOP_IMEM_IRQ				(0)
#define FABRIC_SYS_IRQ				(0)
#define FABRIC_APPS_IRQ				(0)
#define USB1_HS_BAM_IRQ				(0)
#define SDC4_BAM_IRQ				(0)
#define SDC3_BAM_IRQ				(0)
#define SDC2_BAM_IRQ				(0)
#define SDC1_BAM_IRQ				(0)
#define FABRIC_SPS_IRQ				(0)
#define USB1_HS_IRQ				(0)
#define SDC4_IRQ_0				(0)
#define SDC3_IRQ_0				(0)
#define SDC2_IRQ_0				(0)
#define SDC1_IRQ_0				(0)
#define SPS_BAM_DMA_IRQ				(0)
#define SPS_SEC_VIOL_IRQ			(0)
#define SPS_MTI_0				(0)
#define SPS_MTI_1				(0)
#define SPS_MTI_2				(0)
#define SPS_MTI_3				(0)
#define SPS_MTI_4				(0)
#define SPS_MTI_5				(0)
#define SPS_MTI_6				(0)
#define SPS_MTI_7				(0)
#define SPS_MTI_8				(0)
#define SPS_MTI_9				(0)
#define SPS_MTI_10				(0)
#define SPS_MTI_11				(0)
#define SPS_MTI_12				(0)
#define SPS_MTI_13				(0)
#define SPS_MTI_14				(0)
#define SPS_MTI_15				(0)
#define SPS_MTI_16				(0)
#define SPS_MTI_17				(0)
#define SPS_MTI_18				(0)
#define SPS_MTI_19				(0)
#define SPS_MTI_20				(0)
#define SPS_MTI_21				(0)
#define SPS_MTI_22				(0)
#define SPS_MTI_23				(0)
#define SPS_MTI_24				(0)
#define SPS_MTI_25				(0)
#define SPS_MTI_26				(0)
#define SPS_MTI_27				(0)
#define SPS_MTI_28				(0)
#define SPS_MTI_29				(0)
#define SPS_MTI_30				(0)
#define SPS_MTI_31				(0)
#define CSIPHY_4LN_IRQ				(0)
#define MSM8960_CSIPHY_2LN_IRQ			(0)
#define USB2_IRQ				(0)
#define USB1_IRQ				(0)
#define TSSC_SSBI_IRQ				(0)
#define TSSC_SAMPLE_IRQ				(0)
#define TSSC_PENUP_IRQ				(0)
#define MSM8960_GSBI1_UARTDM_IRQ		(0)

/*  l2vic interrupt 65 comes out on 97 under H2  */
#define MSM8960_GSBI1_QUP_IRQ			(32 + 65 + 1)

#define MSM8960_GSBI2_UARTDM_IRQ		(0)
#define MSM8960_GSBI2_QUP_IRQ		        (0)
#define GSBI3_UARTDM_IRQ			(0)
#define GSBI3_QUP_IRQ				(0)
#define GSBI4_UARTDM_IRQ			(0)
#define GSBI4_QUP_IRQ				(0)
#define GSBI5_UARTDM_IRQ			(0)
#define GSBI5_QUP_IRQ				(0)
#define GSBI6_UARTDM_IRQ			(0)
#define GSBI6_QUP_IRQ				(0)
#define GSBI7_UARTDM_IRQ			(0)
#define GSBI7_QUP_IRQ				(0)
#define GSBI8_UARTDM_IRQ			(0)
#define GSBI8_QUP_IRQ				(0)
#define TSIF_TSPP_IRQ				(0)
#define TSIF_BAM_IRQ				(0)
#define TSIF2_IRQ				(0)
#define TSIF1_IRQ				(0)
#define DSI2_IRQ				(0)
#define ISPIF_IRQ				(0)
#define MSMC_SC_SEC_TMR_IRQ			(0)
#define MSMC_SC_SEC_WDOG_BARK_IRQ		(0)
#define ADM_0_SCSS_0_IRQ			(0)
#define ADM_0_SCSS_1_IRQ			(0)
#define ADM_0_SCSS_2_IRQ			(0)
#define ADM_0_SCSS_3_IRQ			(0)
#define CC_SCSS_WDT1CPU1BITEEXPIRED		(0)
#define CC_SCSS_WDT1CPU0BITEEXPIRED		(0)
#define CC_SCSS_WDT0CPU1BITEEXPIRED		(0)
#define CC_SCSS_WDT0CPU0BITEEXPIRED		(0)
#define TSENS_UPPER_LOWER_INT			(0)
#define SSBI2_2_SC_CPU1_SECURE_INT		(0)
#define SSBI2_2_SC_CPU1_NON_SECURE_INT		(0)
#define SSBI2_1_SC_CPU1_SECURE_INT		(0)
#define SSBI2_1_SC_CPU1_NON_SECURE_INT		(0)
#define XPU_SUMMARY_IRQ				(0)
#define BUS_EXCEPTION_SUMMARY_IRQ		(0)
#define HSDDRX_EBI1CH0_IRQ			(0)
#define HSDDRX_EBI1CH1_IRQ			(0)
#define SDC5_BAM_IRQ				(0)
#define SDC5_IRQ_0				(0)
#define GSBI9_UARTDM_IRQ			(0)
#define GSBI9_QUP_IRQ				(0)
#define GSBI10_UARTDM_IRQ			(0)
#define GSBI10_QUP_IRQ				(0)
#define GSBI11_UARTDM_IRQ			(0)
#define GSBI11_QUP_IRQ				(0)
#define GSBI12_UARTDM_IRQ			(0)
#define GSBI12_QUP_IRQ				(0)
#define RIVA_APSS_LTECOEX_IRQ			(0)
#define RIVA_APSS_SPARE_IRQ			(0)
#define RIVA_APSS_WDOG_BITE_RESET_RDY_IRQ	(0)
#define RIVA_APSS_RESET_DONE_IRQ		(0)
#define RIVA_APSS_ASIC_IRQ			(0)
#define RIVA_APPS_WLAN_RX_DATA_AVAIL_IRQ	(0)
#define RIVA_APPS_WLAN_DATA_XFER_DONE_IRQ	(0)
#define RIVA_APPS_WLAN_SMSM_IRQ			(0)
#define RIVA_APPS_LOG_CTRL_IRQ			(0)
#define RIVA_APPS_FM_CTRL_IRQ			(0)
#define RIVA_APPS_HCI_IRQ			(0)
#define RIVA_APPS_WLAN_CTRL_IRQ			(0)
#define A2_BAM_IRQ				(0)
#define SMMU_GFX2D1_CB_SC_SECURE_IRQ		(0)
#define SMMU_GFX2D1_CB_SC_NON_SECURE_IRQ	(0)
#define GFX2D1_IRQ				(0)
#define PPSS_WDOG_TIMER_IRQ			(0)
#define SPS_SLIMBUS_CORE_EE0_IRQ		(0)
#define SPS_SLIMBUS_BAM_EE0_IRQ			(0)
#define QDSS_ETB_IRQ				(0)
#define QDSS_CTI2KPSS_CPU1_IRQ			(0)
#define QDSS_CTI2KPSS_CPU0_IRQ			(0)
#define TLMM_MSM_DIR_CONN_IRQ_16		(0)
#define TLMM_MSM_DIR_CONN_IRQ_17		(0)
#define TLMM_MSM_DIR_CONN_IRQ_18		(0)
#define TLMM_MSM_DIR_CONN_IRQ_19		(0)
#define TLMM_MSM_DIR_CONN_IRQ_20		(0)
#define TLMM_MSM_DIR_CONN_IRQ_21		(0)
#define PM8921_SEC_IRQ_104			(0)
#define PM8018_SEC_IRQ_107			(0)
#define USB_HSIC_IRQ				(0)
#define MSM8960_CSIPHY_2_2LN_IRQ		(0)
#define CSI_2_IRQ				(0)

/* Backwards compatible IRQ macros. */
#define INT_ADM_AARM				0

/* smd/smsm interrupts */
#define INT_A9_M2A_0		(0) /*MSS_TO_APPS_IRQ_0*/
#define INT_A9_M2A_5		(0) /*MSS_TO_APPS_IRQ_1*/
#define INT_ADSP_A11		0
#define INT_ADSP_A11_SMSM	0
#define INT_DSPS_A11		0
#define INT_DSPS_A11_SMSM	0
#define INT_WCNSS_A11		0
#define INT_WCNSS_A11_SMSM	0

#endif

