/*
 * SPDX-License-Identifier: GPL-2.0
 * Kernel module loader support routines for Hexagon
 *
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */
#include <linux/stddef.h>
#include <linux/printk.h>
#include <linux/elf.h>
#include "hexagon_depmask.h"
#include "reloc.h"

/*
 * The structure mirrors the information for relocations specified in the
 * Hexagon ABI Document. Any changes or additions should be reflected in the ABI
 * document, this structure is shared with the Linker and LLVM.
 */
struct hexagon_relocation_info {
	const char *name;
	const uint32_t type;
	const uint32_t effective_bits;
	const uint32_t bitmask;
	const uint32_t alignment;
	const uint32_t shift;
	const bool verify_range;
	const bool verify_alignment;
	const bool is_signed;
};

struct hexagon_relocation_info relocs[] = {
	{
	 /*.name = */ "R_HEX_NONE",
	 /*.type = */ R_HEX_NONE,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_B22_PCREL",
	 /*.type = */ R_HEX_B22_PCREL,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B15_PCREL",
	 /*.type = */ R_HEX_B15_PCREL,
	 /*.effective_bits = */ 15,
	 /*.bitmask = */ 0x00df20fe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B7_PCREL",
	 /*.type = */ R_HEX_B7_PCREL,
	 /*.effective_bits = */ 7,
	 /*.bitmask = */ 0x00001f18,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LO16",
	 /*.type = */ R_HEX_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_HI16",
	 /*.type = */ R_HEX_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_32",
	 /*.type = */ R_HEX_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_16",
	 /*.type = */ R_HEX_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x0000ffff,
	 /*.alignment = */ 2,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_8",
	 /*.type = */ R_HEX_8,
	 /*.effective_bits = */ 8,
	 /*.bitmask = */ 0x000000ff,
	 /*.alignment = */ 1,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GPREL16_0",
	 /*.type = */ R_HEX_GPREL16_0,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 1,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GPREL16_1",
	 /*.type = */ R_HEX_GPREL16_1,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 2,
	 /*.shift = */ 1,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GPREL16_2",
	 /*.type = */ R_HEX_GPREL16_2,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GPREL16_3",
	 /*.type = */ R_HEX_GPREL16_3,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 8,
	 /*.shift = */ 3,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_HL16",
	 /*.type = */ R_HEX_HL16,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_B13_PCREL",
	 /*.type = */ R_HEX_B13_PCREL,
	 /*.effective_bits = */ 13,
	 /*.bitmask = */ 0x00202ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B9_PCREL",
	 /*.type = */ R_HEX_B9_PCREL,
	 /*.effective_bits = */ 9,
	 /*.bitmask = */ 0x003000fe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B32_PCREL_X",
	 /*.type = */ R_HEX_B32_PCREL_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_32_6_X",
	 /*.type = */ R_HEX_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_B22_PCREL_X",
	 /*.type = */ R_HEX_B22_PCREL_X,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B15_PCREL_X",
	 /*.type = */ R_HEX_B15_PCREL_X,
	 /*.effective_bits = */ 15,
	 /*.bitmask = */ 0x00df20fe,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B13_PCREL_X",
	 /*.type = */ R_HEX_B13_PCREL_X,
	 /*.effective_bits = */ 13,
	 /*.bitmask = */ 0x00202ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B9_PCREL_X",
	 /*.type = */ R_HEX_B9_PCREL_X,
	 /*.effective_bits = */ 9,
	 /*.bitmask = */ 0x003000fe,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_B7_PCREL_X",
	 /*.type = */ R_HEX_B7_PCREL_X,
	 /*.effective_bits = */ 7,
	 /*.bitmask = */ 0x00001f18,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_16_X",
	 /*.type = */ R_HEX_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_12_X",
	 /*.type = */ R_HEX_12_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0x7e0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_11_X",
	 /*.type = */ R_HEX_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_10_X",
	 /*.type = */ R_HEX_10_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_9_X",
	 /*.type = */ R_HEX_9_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_8_X",
	 /*.type = */ R_HEX_8_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_7_X",
	 /*.type = */ R_HEX_7_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_6_X",
	 /*.type = */ R_HEX_6_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_32_PCREL",
	 /*.type = */ R_HEX_32_PCREL,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_COPY",
	 /*.type = */ R_HEX_COPY,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GLOB_DAT",
	 /*.type = */ R_HEX_GLOB_DAT,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_JMP_SLOT",
	 /*.type = */ R_HEX_JMP_SLOT,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_RELATIVE",
	 /*.type = */ R_HEX_RELATIVE,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_PLT_B22_PCREL",
	 /*.type = */ R_HEX_PLT_B22_PCREL,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOTREL_LO16",
	 /*.type = */ R_HEX_GOTREL_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOTREL_HI16",
	 /*.type = */ R_HEX_GOTREL_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOTREL_32",
	 /*.type = */ R_HEX_GOTREL_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOT_LO16",
	 /*.type = */ R_HEX_GOT_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOT_HI16",
	 /*.type = */ R_HEX_GOT_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOT_32",
	 /*.type = */ R_HEX_GOT_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOT_16",
	 /*.type = */ R_HEX_GOT_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_DTPMOD_32",
	 /*.type = */ R_HEX_DTPMOD_32,
	 /*.effective_bits = */ 0,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 0,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_LO16",
	 /*.type = */ R_HEX_DTPREL_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_HI16",
	 /*.type = */ R_HEX_DTPREL_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_32",
	 /*.type = */ R_HEX_DTPREL_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_16",
	 /*.type = */ R_HEX_DTPREL_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_PLT_B22_PCREL",
	 /*.type = */ R_HEX_GD_PLT_B22_PCREL,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_LO16",
	 /*.type = */ R_HEX_GD_GOT_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_HI16",
	 /*.type = */ R_HEX_GD_GOT_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_32",
	 /*.type = */ R_HEX_GD_GOT_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_16",
	 /*.type = */ R_HEX_GD_GOT_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_LO16",
	 /*.type = */ R_HEX_IE_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_HI16",
	 /*.type = */ R_HEX_IE_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_32",
	 /*.type = */ R_HEX_IE_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_LO16",
	 /*.type = */ R_HEX_IE_GOT_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_HI16",
	 /*.type = */ R_HEX_IE_GOT_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_32",
	 /*.type = */ R_HEX_IE_GOT_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_16",
	 /*.type = */ R_HEX_IE_GOT_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_LO16",
	 /*.type = */ R_HEX_TPREL_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_HI16",
	 /*.type = */ R_HEX_TPREL_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_32",
	 /*.type = */ R_HEX_TPREL_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_16",
	 /*.type = */ R_HEX_TPREL_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_6_PCREL_X",
	 /*.type = */ R_HEX_6_PCREL_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GOTREL_32_6_X",
	 /*.type = */ R_HEX_GOTREL_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOTREL_16_X",
	 /*.type = */ R_HEX_GOTREL_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GOTREL_11_X",
	 /*.type = */ R_HEX_GOTREL_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GOT_32_6_X",
	 /*.type = */ R_HEX_GOT_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOT_16_X",
	 /*.type = */ R_HEX_GOT_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GOT_11_X",
	 /*.type = */ R_HEX_GOT_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_32_6_X",
	 /*.type = */ R_HEX_DTPREL_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_16_X",
	 /*.type = */ R_HEX_DTPREL_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_DTPREL_11_X",
	 /*.type = */ R_HEX_DTPREL_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_32_6_X",
	 /*.type = */ R_HEX_GD_GOT_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_16_X",
	 /*.type = */ R_HEX_GD_GOT_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GD_GOT_11_X",
	 /*.type = */ R_HEX_GD_GOT_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_IE_32_6_X",
	 /*.type = */ R_HEX_IE_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_16_X",
	 /*.type = */ R_HEX_IE_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_32_6_X",
	 /*.type = */ R_HEX_IE_GOT_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_16_X",
	 /*.type = */ R_HEX_IE_GOT_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_IE_GOT_11_X",
	 /*.type = */ R_HEX_IE_GOT_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_32_6_X",
	 /*.type = */ R_HEX_TPREL_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_16_X",
	 /*.type = */ R_HEX_TPREL_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_TPREL_11_X",
	 /*.type = */ R_HEX_TPREL_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_LD_PLT_B22_PCREL",
	 /*.type = */ R_HEX_LD_PLT_B22_PCREL,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_LO16",
	 /*.type = */ R_HEX_LD_GOT_LO16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_HI16",
	 /*.type = */ R_HEX_LD_GOT_HI16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0x00c03fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 16,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_32",
	 /*.type = */ R_HEX_LD_GOT_32,
	 /*.effective_bits = */ 32,
	 /*.bitmask = */ 0xffffffff,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_16",
	 /*.type = */ R_HEX_LD_GOT_16,
	 /*.effective_bits = */ 16,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ true,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_32_6_X",
	 /*.type = */ R_HEX_LD_GOT_32_6_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_16_X",
	 /*.type = */ R_HEX_LD_GOT_16_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_LD_GOT_11_X",
	 /*.type = */ R_HEX_LD_GOT_11_X,
	 /*.effective_bits = */ 6,
	 /*.bitmask = */ 0,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_23_REG",
	 /*.type = */ R_HEX_23_REG,
	 /*.effective_bits = */ 21,
	 /*.bitmask = */ 0x0fff3fe0,
	 /*.alignment = */ 4,
	 /*.shift = */ 2,
	 /*.verify_range = */ true,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ false,
	 },
	{
	 /*.name = */ "R_HEX_GD_PLT_B22_PCREL_X",
	 /*.type = */ R_HEX_GD_PLT_B22_PCREL_X,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_GD_PLT_B32_PCREL_X",
	 /*.type = */ R_HEX_GD_PLT_B32_PCREL_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LD_PLT_B22_PCREL_X",
	 /*.type = */ R_HEX_LD_PLT_B22_PCREL_X,
	 /*.effective_bits = */ 22,
	 /*.bitmask = */ 0x01ff3ffe,
	 /*.alignment = */ 4,
	 /*.shift = */ 0,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 },
	{
	 /*.name = */ "R_HEX_LD_PLT_B32_PCREL_X",
	 /*.type = */ R_HEX_LD_PLT_B32_PCREL_X,
	 /*.effective_bits = */ 26,
	 /*.bitmask = */ 0x0fff3fff,
	 /*.alignment = */ 4,
	 /*.shift = */ 6,
	 /*.verify_range = */ false,
	 /*.verify_alignment = */ false,
	 /*.Signed = */ true,
	 }
};

static uint32_t
find_bitmask_helper(uint32_t insn, struct hexagon_instruction *encodings,
		    int32_t num_insns)
{
	int32_t i;

	for (i = 0; i < num_insns; i++) {
		if (((insn & 0xc000) == 0) && !(encodings[i].is_duplex))
			continue;

		if (((insn & 0xc000) != 0) && (encodings[i].is_duplex))
			continue;

		if (((encodings[i].mask) & insn) ==
		    encodings[i].cmpmask) {
			return encodings[i].bitmask;
		}
	}
	pr_err("Cannot find encoding for Instruction: 0x%x\n", insn);
	return 0;
}

/*
 * Find the bitmask by calling the helper function. In future this function may
 * take the architecture and traverse different encodings per architecture.
 */
static uint32_t
find_mask(uint32_t insn)
{
	return find_bitmask_helper((uint32_t)insn, insn_encodings,
				   sizeof(insn_encodings) /
				   sizeof(struct hexagon_instruction));
}

static uint32_t
apply_mask(uint32_t mask, uint32_t data)
{
	uint32_t result = 0;
	size_t offset = 0;
	size_t bit;

	for (bit = 0; bit != sizeof(uint32_t) * 8; ++bit) {
		const bool val_bit = (data >> offset) & 1;
		const bool mask_bit = (mask >> bit) & 1;
		if (mask_bit) {
			result |= (val_bit << bit);
			++offset;
		}
	}
	return result;
}

/*
 * The relocation helper function that computes the insn bits with the
 * relocation applied.
 */
static uint32_t
do_reloc_helper_unsigned(uint32_t reloc_type, uint32_t insn, uint32_t value)
{
	uint32_t value_after_shift = value >> relocs[reloc_type].shift;
	uint32_t effective_value =
	    value_after_shift & (~0U >>
				 (32 - relocs[reloc_type].effective_bits));
	uint32_t bitmask = relocs[reloc_type].bitmask;

	if (bitmask == 0) {
		bitmask = find_mask(insn);
		if (bitmask == 0)
			return 0;
	}
	insn &= ~bitmask;
	effective_value = apply_mask(bitmask, effective_value);
	return effective_value | insn;
}

/*
 * The relocation helper function that computes the insn bits with the
 * relocation applied.
 */
static uint32_t
do_reloc_helper_signed(uint32_t reloc_type, uint32_t insn, int32_t value)
{
	int32_t value_after_shift = value >> relocs[reloc_type].shift;
	uint32_t effective_value =
	    value_after_shift & (~0U >>
				 (32 - relocs[reloc_type].effective_bits));
	uint32_t bitmask = relocs[reloc_type].bitmask;

	if (bitmask == 0) {
		bitmask = find_mask(insn);
		if (bitmask == 0)
			return 0;
	}
	insn &= ~bitmask;
	effective_value = apply_mask(bitmask, effective_value);
	return effective_value | insn;
}

/* This function finds the mask for the insn and applies the mask. */
uint32_t
do_reloc(uint32_t reloc_type, uint32_t insn, uint32_t value)
{
	if (relocs[reloc_type].is_signed)
		return do_reloc_helper_signed(reloc_type, insn, value);
	else
		return do_reloc_helper_unsigned(reloc_type, insn, value);
}
